#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Nov 11, 2021 05:20:09 PM EET  platform: Linux

import sys
from tkinter.filedialog import askopenfilename

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import main_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    main_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None





class Toplevel1:

    def open_file(self):
        pcap_file = askopenfilename(defaultextension='.pcap', filetypes=[
            (".pcap", ".pcapng")])  # show an "Open" dialog box and return the path to the selected file
        print(pcap_file)
        # the source of the packets
        # pcap_file = 'sip_only.pcapng'
        # capture = pyshark.FileCapture(pcap_file)

        self.Label2.configure(text=pcap_file)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        pcap_file = '''The file hasn't been chosen.'''
        top.geometry("610x480+645+330")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("SIPp generator")
        top.configure(highlightcolor="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.367, rely=0.221, height=31, width=151)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(cursor="gobbler")
        self.Button1.configure(text='''Choose a .pcap file''')
        self.Button1.configure(command=self.open_file)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.033, rely=0.09, height=33, width=567)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font="-family {Tlwg Typewriter} -size 15 -weight bold")
        self.Label1.configure(text='''SIPp scripts generator''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.033, rely=0.288, height=33, width=556)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(cursor="fleur")
        self.Label2.configure(font="-family {Tlwg Typewriter} -size 12")
        self.Label2.configure(text=pcap_file)

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.033, rely=0.445, relheight=0.169
                , relwidth=0.931)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(cursor="fleur")
        self.Listbox1.configure(font="-family {Tlwg Typewriter} -size 10")
        self.Listbox1.configure(selectbackground="#4603ff")
        self.Listbox1.configure(selectforeground="white")
        self.Listbox1.configure(setgrid="1")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.411, rely=0.668, height=31, width=91)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(cursor="gobbler")
        self.Button2.configure(text='''Generate''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.033, rely=0.378, height=23, width=111)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(cursor="fleur")
        self.Label3.configure(font="-family {Tlwg Typewriter} -size 12")
        self.Label3.configure(text='''Call-IDs:''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.033, rely=0.731, height=34, width=149)
        self.Label4.configure(cursor="fleur")
        self.Label4.configure(font="-family {Tlwg Typewriter} -size 12")
        self.Label4.configure(text='''Log messages:''')

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.033, rely=0.797, relheight=0.169, relwidth=0.931)

        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {Tlwg Typewriter} -size 10")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

if __name__ == '__main__':
    vp_start_gui()





